### PR TITLE
Webtorrent WebRTC seed

### PR DESCRIPTION
**Pull request by jhiesey**
This depends on and should be merged after https://github.com/webtorrent/bittorrent-tracker/pull/286

### CODE REVIEW

**Comment by mitra42** [comment]
Hi John 
Sorry for radio-silence, was doing the relocation back to Australia, If I understand the comments above, I should be able to npm update to the latest webtorrent, then merge this release, and it should just work ... is that correct ?

**Comment by mitra42** [comment]
Great - I'll do this.

**Comment by mitra42** [comment]
Can you clarify the suggestion for testing it... 
If I `cd /usr/local/dweb-transport; npm run test `
Then I get a EADDRINUSE 

Can you clarify what you had in mind?

**Comment by jhiesey** [comment]
Yeah, something like this: https://gist.github.com/jhiesey/e54bd3e98faf09d6775c6b1396e34605

put that in something like test/runtime-test.js and run it with node.

**Comment by jhiesey** [comment]
Basically that's just the third test without the running the seeder or tracker since you already have those running.

**Comment by jhiesey** [comment]
That's what you mean, right?

**Comment by mitra42** [comment]
Ah ok - that makes sense, I was running the full test set, and it was reporting EADDRINUSE and the issue was probably the earlier tests starting a new Tracker on same port as live one.

**Comment by jhiesey** [comment]
Ideally we would change the ports in the tests. Then you could run the existing tests on different ports and not conflict with the live one. We could then configure a separate test to test against the live server to make sure things work in that configuration too.

**Comment by mitra42** [comment]
RIght - and I just tried the last step (test against live server) but it is failing, and I'm not sure how to figure out where.

**Comment by jhiesey** [comment]
What happens?

**Comment by mitra42** [comment]
Nothing - I'm testing on my laptop
```
mitraglass:test mitra$ node ./seedertest.js
(node:76770) Warning: N-API is an experimental feature and could change at any time.
TAP version 13
# download torrent through seeder via WebRTC
```
But I'm seeing activity on the log in dweb.me:/var/log/dweb/dweb-seeder, so it might just be slow - it might be good if the test was a bit more verbose. 

Last thing in logs (I'm tailing seeder and tracker)  is
```
2018-08-15T05:30:23.186Z bittorrent-protocol [1646478d] keep-alive
2018-08-15T05:30:23.186Z bittorrent-protocol [2c87e77e] got keep-alive
2018-08-15T05:30:35.491Z webtorrent:peer destroy 2d5757303030322d384745324b6c4b512b69336a (error: connect timeout)
2018-08-15T05:30:35.491Z simple-peer [d04f070] destroy (error: undefined)
2018-08-15T05:30:35.506Z webtorrent:torrent [2d57573] [22cf567] removePeer 2d5757303030322d384745324b6c4b512b69336a
2018-08-15T05:30:35.507Z webtorrent:torrent [2d57573] [22cf567] _drain numConns 1 maxConns 55
2018-08-15T05:30:35.507Z webtorrent:torrent [2d57573] [22cf567] drain (0 queued, 1/55 peers)
2018-08-15T05:30:59.721Z bittorrent-tracker:websocket-tracker tracker timeout: destroying peer
2018-08-15T05:30:59.722Z simple-peer [8df1943] destroy (error: undefined)
2018-08-15T05:30:59.735Z bittorrent-tracker:websocket-tracker tracker timeout: destroying peer

```

**Comment by mitra42** [comment]
It might just be slow, that torrent is large and I think its getting the whole thing. because I'm seeing activity again in the logs.

**Comment by jhiesey** [comment]
Try `DEBUG="webtorrent:*" node ./seedertest.js`

Or for even more output, `DEBUG="*" node ./seedertest.js`

**Comment by mitra42** [comment]
Will do ... and will run on the server machine, my home internet here is too slow for a massive file. 

Note ... it seems to require
```
sudo apt-get install xvfb
```
to run electron

**Comment by mitra42** [comment]
Still failing 
```
mitra@wwwb-dev0:/usr/local/dweb-transport/test$ 
mitra@wwwb-dev0:/usr/local/dweb-transport/test$ DEBUG="webtorrent:*" node ./seedertest.js
(node:6639) Warning: N-API is an experimental feature and could change at any time.
TAP version 13
# download torrent through seeder via WebRTC
  webtorrent:tcp-pool create tcp pool (port 0) +0ms
  webtorrent:torrent [2d57573] [22cf567] new torrent +0ms
  webtorrent:torrent [2d57573] [22cf567] got metadata +25ms
  webtorrent:torrent [2d57573] [22cf567] select 0-139 (priority 0) +5ms
  webtorrent:torrent [2d57573] [22cf567] verifying existing torrent data +1ms
  webtorrent:torrent [2d57573] [22cf567] done verifying +50ms
  webtorrent:torrent [2d57573] [22cf567] on store +0ms
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: electron-eval error: Electron process exited with code 127.
Stderr:
/usr/local/dweb-transport/node_modules/electron/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

    at ChildProcess.<anonymous> (/usr/local/dweb-transport/node_modules/electron-eval/lib/index.js:174:22)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
Emitted 'error' event at:
    at Daemon.error (/usr/local/dweb-transport/node_modules/electron-eval/lib/index.js:101:12)
    at ChildProcess.<anonymous> (/usr/local/dweb-transport/node_modules/electron-eval/lib/index.js:174:16)
    at ChildProcess.emit (events.js:180:13)
    [... lines matching original stack trace ...]
    at Pipe._handle.close [as _onclose] (net.js:541:12)
mitra@wwwb-dev0:/usr/local/dweb-transport/test$
```

**Comment by mitra42** [comment]
Looks like electron isn't as easy to run as you thought :-)

**Comment by jhiesey** [comment]
Let's just switch everything to `wrtc`

**Comment by jhiesey** [comment]
I can make the changes if you want. Just a sec.

**Comment by mitra42** [comment]
Looks like that worked - test completed successfully and file downloaded

**Comment by mitra42** [comment]
One question - is the Tracker telling the world the Seeder is at localhost:6969 as I'm not seeing where we tell the Tracker where to tell the world the Seeder is. (I'm presuming the `localhost:6969` is needed for the Seeder to communicate with the Tracker somehow for the Webrtc ?

**Comment by jhiesey** [comment]
https://github.com/jhiesey/dweb-transport/blob/master/seeder-config.json#L9 configures where the seeder finds the tracker, so the seeder gets a websocket connection to the tracker.

The tracker then recognizes the connection from the seeder as special here: https://github.com/jhiesey/dweb-transport/blob/master/tracker/index.js Localhost is assumed to be where the connection is coming from unless an "ip" field is added to the peer entry object in seeder-config.json

**Comment by jhiesey** [comment]
The tracker doesn't ever actually tell the world the seeder's ip address. It doesn't have to. It just forwards the WebRTC offers/answers from the seeder to the user's client and vice versa.

**Comment by jhiesey** [comment]
To be more precise, the offers/answers themselves contain the seeder's ip address.

**Comment by mitra42** [comment]
I thought the point of WebRTC was that the user's client then opens a WebRTC connection to the user's client.  Which will only work if the offer/answer has the real external IP address, not localhost or the NATed address.  

If a normal Seeder contacts a Tracker then The Tracker is going to see the real external IP address (and port) of the Seeder, but if it connects via localhost the Seeder doesn't know what that address is to tell the Tracker ?

**Comment by jhiesey** [comment]
A webrtc client has to query a STUN server which tells it's external ip address. That's the ip address that actually gets put into the offer (actually it's a bit more complicated so that it can work directly on a local network too; offers can include the local ip address).

The tracker just hands the offers/answers off as blobs between the seeder and the client. In other words, normally, a webtorrent tracker doesn't care what the ip addresses of the clients connected to it. Only in this case I want to recognize one client (the seeder) to treat specially.

As for the regular bittorrent protocol, you do have to put the external seeder ip in seeder-config.json

**Comment by jhiesey** [comment]
The default STUN servers are actually set here (in case you're curious): https://github.com/feross/simple-peer/blob/master/index.js#L157-L160

**Comment by mitra42** [comment]
Thanks - I didn't know about the STUN servers, I thought it was the Tracker performing that role. 

I still don't understand what you mean by: 
`As for the regular bittorrent protocol, you do have to put the external seeder ip in seeder-config.json`

Where?

**Comment by mitra42** [comment]
By the way ... looks like dweb.archive.org is down, I've got to focus on fixing that bfore I have to go to a meeting in 30 mins :-(

**Comment by jhiesey** [comment]
Like
```js
{
  "superPeers": [
    {
      "peerId": "2d5757303039382d494c414465783166346c7351",
      "torrentPort": 6881,
      "wrtc": "wrtc"
    }
  ]
...
}

**Comment by jhiesey** [comment]
Sorry edited comment

**Comment by mitra42** [comment]
Ok - and presumably that is the IP address of the server itself, not of the machine that is proxying wss into ws

**Comment by jhiesey** [comment]
Yes

**Comment by mitra42** [comment]
Ok - that should be live now

**Comment by mitra42** [comment]
Had to get teh site back up - looks like an upgrade in the readable-stream broke things, going back to 2.3.6 solved it.

**Comment by jhiesey** [comment]
I tried downloading a torrent with both regular bittorrent and WebRTC and neither seems to actually work. With regular bittorrent the tracker seems to be returning 127.0.0.1 as the seeder ip. Is the superPeer ip not configured?

With WebRTC, the tracker socket seems to close if 'wss://dweb.me:4245' is used as the tracker. I'm not sure what's going on, but one guess is that the nginx proxy isn't setting the `x-forwarded-for` header that the tracker is expecting, so the tracker thinks every connection is from the super peer.

With WebRTC and 'ws://dweb.me:6969' as the tracker, things get very close but the connection between my machine and the seeder doesn't work. Could that be a firewall issue? WebRTC wants to listen on lots of high ports.

**Pull request merged**
